walruswalrus:
  build: .
  command: node index.js
  container_name: walruswalrus
  ports:
    - '80:80'
    - '8080:8080'
  volumes:
    - .:/usr/src
    - /usr/src/node_modules
coturn:
  build: docker-turnserver
  container_name: coturn
  command: bash -c "service coturn start && tail -f /dev/null"
  tty: true
  ports:
    - '3478:3478'
    - '3478:3478/udp'
